---
- name: Set Password
  hosts: DMZ-Linux
  become: yes

  tasks:
  - name: Check if user exists
    shell: id -u administrator
    register: user_exists
    ignore_errors: true

  - name: Change Password
    user:
      name: administrator
      password: "$1$3Zdze7Vx$g9D87GRvyRGyEIDKXrMaF0"
      update_password: always
    when: user_exists
